Fix back navigation to details page
drobnikj/crawler-google-places pull request #138
Opened 2021-05-12 13:32 UTC by mattiashtd

Clicking the back button on the additional info page and on the review page often had no effect which resulted in errors afterwards.
Fix this by clicking the back button repeatedly if the navigation doesn't take place.

2021-05-12 18:21 UTC, metalwarrior665 requested changes
This is amazing, thanks a ton! Please just check my comment. Also, do you know how often it still completely timeouts/gets stuck?

2021-05-12 18:21 UTC, metalwarrior665 commented on src/extractors.js
> +            const title = await page.$(PLACE_TITLE_SEL);
Maybe I would put this check also to the navigateBack function so it always first checks if we are on the main page (no navigation needed) and only if not then starts to wait for the back button

2021-05-17 08:40 UTC, mattiashtd commented on src/extractors.js
> +            const title = await page.$(PLACE_TITLE_SEL);
Sure, fixed here: c617346dba2b447e55d0bb3837306488f51b8ced
Sorry for being late - I was on holidays :)

2021-05-17 08:44 UTC, mattiashtd commented on src/extractors.js
> +            const title = await page.$(PLACE_TITLE_SEL);
> Also, do you know how often it still completely timeouts/gets stuck?

After the fix it didn't time out anymore for me. But I only checked it for a small amount of pages until now. Usually the click worked on the 2nd time latest. I think it never clicked 4 times or more.

2021-05-17 10:04 UTC, mattiashtd commented on src/extractors.js
> +            const title = await page.$(PLACE_TITLE_SEL);
Oops, now really fixed with this: 6ab80a4a64491aaaf00515b4273c520b05166e48 
My brain wasn't fully back from my holidays :)

2021-05-17 12:33 UTC, metalwarrior665 commented
Thanks. Merging it in. We will test it a bit in beta on Apify.

2021-05-17 12:33 UTC, merged