OCR upgrade
drobnikj/crawler-google-places pull request #257
Opened 2022-04-25 23:17 UTC by apify-alexey

- actor will not fall back to mouse-move results in case if OCR found 0 pins
- Input UI changed to single drop-down below main options, internally `allPlacesNoSearch` still applied for backwards compatibility
I can upgrade SDK as part of this PR, please let me know if I can proceed with upgrade

2022-04-26 10:47 UTC, metalwarrior665 requested changes
Few small comments

2022-04-26 10:47 UTC, metalwarrior665 commented on INPUT_SCHEMA.json
> +                "NOT APPLIED",
1. I think we don't need upper case, it will just scare users :)
2. I would add explanation `Not applied (normal search or direct places)`

2022-04-26 10:47 UTC, metalwarrior665 commented on src/main.js
>      }
Please move the backward compat logic to `makeInputBackwardsCompatible` function and look there how we deprecate stuff

2022-05-02 08:35 UTC, apify-alexey commented
@metalwarrior665 changes applied, thanks for pointing out

2022-05-04 12:40 UTC, metalwarrior665 approved these changes

2022-05-04 12:41 UTC, merged