Fix/update dependencies
drobnikj/crawler-google-places pull request #274
Opened 2022-06-24 18:07 UTC by lhotanok

2022-06-25 20:44 UTC, pocesar requested changes
looks very good, thanks for also updating the comments and docs @lhotanok after merge, going to do `beta` on platform

2022-06-25 20:44 UTC, pocesar commented on src/enqueue_places.js
> +            await retryClickSearchButton?.evaluate(b => b.click());
this should fail so the `catch` block can be reached for the fallback submit. but a more explicit `throw` here might be better

2022-06-25 20:44 UTC, pocesar commented on src/main.js
> +     const stealthOptionsWrapper = {
since stealth is deprecated, I think we can get rid of it altogether

2022-06-26 20:56 UTC, lhotanok commented on src/main.js
> +     const stealthOptionsWrapper = {
Yeah, I was thinking the same but wasn't sure

2022-06-27 03:48 UTC, pocesar approved these changes

2022-06-27 14:25 UTC, metalwarrior665 approved these changes
Looks good but we should test more as there are a lot of small changes

2022-06-27 14:25 UTC, merged